### PR TITLE
Make emblem template compatible with ember-handlebars-template 0.7.0

### PR DESCRIPTION
**Pull request by Eric-Guo**
Appreciate if can release a new version.

### CODE REVIEW

**Comment by botandrose** [comment]
Hi @Eric-Guo, thanks for the PR! The tests are broken, so I won't merge this as it is, but let me know if you get the tests passing, and I'll take another look.

**Comment by Eric-Guo** [comment]
@botandrose Now test passed, seems the methods of `def template_path` method in ember-handlebars-template implementation changed.

**Comment by Eric-Guo** [comment]
@botandrose Now test passed, seems the methods of `def template_path` method in ember-handlebars-template implementation changed.

**Comment by botandrose** [comment]
Hi @Eric-Guo sorry its taken so long for me to review this. I don't have any projects that use this library anymore, so its difficult for me to evaluate it. I'll do my best to evaluate it today.

**Comment by botandrose** [comment]
@Eric-Guo It appears to work! Merging. Thank you!

**Comment by botandrose** [comment]
https://rubygems.org/gems/ember-emblem-template/versions/0.4.0

**Pull request merged**
